class_name GRef
extends Node

static var GROUP_INTERACTIBLE_PICKUPABLE: String = "GROUP_INTERACTIBLE_PICKUPABLE"
static var GROUP_INTERACTIBLE_OBJECT: String = "GROUP_INTERACTIBLE_OBJECT"
static var GROUP_ITEM_WEAPON: String = "GROUP_ITEM_WEAPON"
